# Generated by Django 5.2.9 on 2025-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JulesSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_encrypted_api_key", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jules Settings",
                "verbose_name_plural": "Jules Settings",
                "db_table": "jules_settings",
            },
        ),
    ]
