# Generated by Django 5.2.9 on 2025-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jules", "0003_reencrypt_api_keys_dedicated_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="JulesSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        blank=True, default="STATE_UNSPECIFIED", max_length=32
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("source", models.TextField(blank=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jules_sessions",
            },
        ),
        migrations.CreateModel(
            name="JulesActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("plan_generated", "Plan Generated"),
                            ("plan_approved", "Plan Approved"),
                            ("progress_updated", "Progress Updated"),
                            ("session_completed", "Session Completed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="jules.julessession",
                    ),
                ),
            ],
            options={
                "db_table": "jules_activities",
            },
        ),
        migrations.AddIndex(
            model_name="julesactivity",
            index=models.Index(
                fields=["session", "create_time"], name="jules_acti_session_9fdaaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="julesactivity",
            index=models.Index(
                fields=["activity_type"], name="jules_acti_activity_6ef967_idx"
            ),
        ),
    ]
