# Generated by Django 5.2.9 on 2025-12-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jules", "0007_reencrypt_api_keys_jules_encryption_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="julessession",
            index=models.Index(
                fields=["last_synced_at"], name="jules_sess_last_sy_62f37b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="julesactivity",
            index=models.Index(
                fields=["last_synced_at"], name="jules_acti_last_sy_353f8c_idx"
            ),
        ),
    ]
