# Generated by Django 6.0.1 on 2026-02-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jules", "0008_sync_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="julesactivity",
            new_name="jules_activ_session_feb629_idx",
            old_name="jules_acti_session_9fdaaf_idx",
        ),
        migrations.RenameIndex(
            model_name="julesactivity",
            new_name="jules_activ_activit_9cbe6a_idx",
            old_name="jules_acti_activity_6ef967_idx",
        ),
        migrations.RenameIndex(
            model_name="julesactivity",
            new_name="jules_activ_last_sy_f304cf_idx",
            old_name="jules_acti_last_sy_353f8c_idx",
        ),
        migrations.RenameIndex(
            model_name="julessession",
            new_name="jules_sessi_last_sy_a648e9_idx",
            old_name="jules_sess_last_sy_62f37b_idx",
        ),
    ]
