# Generated by Django 5.2.9 on 2025-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JulesSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(max_length=32)),
                ("prompt", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "jules_sessions",
            },
        ),
        migrations.CreateModel(
            name="JulesActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("activity_type", models.CharField(blank=True, max_length=64)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="jules.julessession")),
            ],
            options={
                "db_table": "jules_activities",
            },
        ),
        migrations.AddConstraint(
            model_name="julesactivity",
            constraint=models.UniqueConstraint(fields=("session", "name"), name="unique_jules_activity"),
        ),
    ]
