# Generated by Django 5.2.9 on 2025-12-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jules", "0002_add_sessions_activities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="julessession",
            name="state",
            field=models.CharField(
                max_length=32,
                choices=[
                    ("STATE_UNSPECIFIED", "Unspecified"),
                    ("STATE_ACTIVE", "Active"),
                    ("STATE_COMPLETED", "Completed"),
                    ("STATE_FAILED", "Failed"),
                ],
                default="STATE_UNSPECIFIED",
            ),
        ),
        migrations.AddIndex(
            model_name="julessession",
            index=models.Index(fields=["update_time"], name="jules_sessi_update__idx"),
        ),
        migrations.AddIndex(
            model_name="julessession",
            index=models.Index(fields=["last_synced_at"], name="jules_sessi_last_sy_idx"),
        ),
    ]
